import type { Language } from "@/i18n/languages";

export const muzaCopy = {
	en: {
		beta: "NEW",
		clear: "Clear history",
		clearCancel: "Cancel",
		clearConfirm: "Clear",
		clearPrompt: "Clear Muza chat history?",
		clearSuccess: "Muza history cleared.",
		copy: "Copy response",
		copySuccess: "Copied to clipboard.",
		error: "Muza could not answer right now.",
		greeting: "Hi, I am Muza.",
		partial: "Response may be incomplete.",
		placeholder: "Ask Muza for quiz ideas, hints, or help with a topic...",
		ready: "Ready",
		send: "Send message",
		subtitle: "Sofinka helper",
		thinking: "Thinking...",
		title: "Muza Assistant",
		waiting: "Working on it...",
		writing: "Writing response...",
	},
	uk: {
		beta: "НОВЕ",
		clear: "Очистити історію",
		clearCancel: "Скасувати",
		clearConfirm: "Очистити",
		clearPrompt: "Очистити історію чату з Музою?",
		clearSuccess: "Історію Музи очищено.",
		copy: "Скопіювати відповідь",
		copySuccess: "Скопійовано.",
		error: "Муза зараз не змогла відповісти.",
		greeting: "Привіт, я Муза.",
		partial: "Відповідь може бути неповною.",
		placeholder: "Запитай Музу про ідеї для вікторини, підказки або тему...",
		ready: "Готова",
		send: "Надіслати повідомлення",
		subtitle: "помічниця Sofinka",
		thinking: "Думаю...",
		title: "Асистентка Муза",
		waiting: "Думаю...",
		writing: "Пишу відповідь...",
	},
	ru: {
		beta: "НОВОЕ",
		clear: "Очистить историю",
		clearCancel: "Отмена",
		clearConfirm: "Очистить",
		clearPrompt: "Очистить историю чата с Музой?",
		clearSuccess: "История Музы очищена.",
		copy: "Скопировать ответ",
		copySuccess: "Скопировано.",
		error: "Муза сейчас не смогла ответить.",
		greeting: "Привет, я Муза.",
		partial: "Ответ может быть неполным.",
		placeholder: "Спроси Музу про идеи для квиза, подсказки или тему...",
		ready: "Готова",
		send: "Отправить сообщение",
		subtitle: "помощница Sofinka",
		thinking: "Думаю...",
		title: "Ассистент Муза",
		waiting: "Думаю...",
		writing: "Пишу ответ...",
	},
} satisfies Record<Language, Record<string, string>>;

export function getMuzaCopy(language: Language) {
	return muzaCopy[language];
}
