export const LANGUAGE_CONFIGS = {
	English: {
		code: "en",
		name: "English",
		answer: "Answer",
		concept: "Concept",
		description: "Description",
		imageDescription: "Image description",
		mainTopic: "Main topic",
		other: "Other",
		otherOption: "Other option",
		question: "Question?",
		questionAbout: "Question about",
		shortHint: "Short hint",
		topic: "Topic",
		variant: "Option",
		sortingTitle: "Sort items into groups",
		sortingDescription: "Place each item in the right group",
		group: "Group",
		item: "Item",
		trueLabel: "True",
		falseLabel: "False",
	},
	Ukrainian: {
		code: "uk",
		name: "Ukrainian",
		answer: "Відповідь",
		concept: "Поняття",
		description: "Опис",
		imageDescription: "Опис картинки",
		mainTopic: "Головна тема",
		other: "Інше",
		otherOption: "Інший варіант",
		question: "Запитання?",
		questionAbout: "Запитання про",
		shortHint: "Коротка підказка",
		topic: "Тема",
		variant: "Варіант",
		sortingTitle: "Розклади предмети за групами",
		sortingDescription: "Поклади кожен предмет у правильну групу",
		group: "Група",
		item: "Предмет",
		trueLabel: "Правда",
		falseLabel: "Неправда",
	},
	Russian: {
		code: "ru",
		name: "Russian",
		answer: "Ответ",
		concept: "Понятие",
		description: "Описание",
		imageDescription: "Описание картинки",
		mainTopic: "Главная тема",
		other: "Другой",
		otherOption: "Другой вариант",
		question: "Вопрос?",
		questionAbout: "Вопрос про",
		shortHint: "Короткая подсказка",
		topic: "Тема",
		variant: "Вариант",
		sortingTitle: "Разложи предметы по группам",
		sortingDescription: "Положи каждый предмет в правильную группу",
		group: "Группа",
		item: "Предмет",
		trueLabel: "Правда",
		falseLabel: "Неправда",
	},
};

export function getLanguageConfig(language) {
	const languageName = String(language ?? "").trim();
	return LANGUAGE_CONFIGS[languageName] ?? LANGUAGE_CONFIGS.Russian;
}
