/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConstructorIndexRouteImport } from './routes/constructor.index'
import { Route as ApiGenerateQuestionsRouteImport } from './routes/api/generate-questions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructorIndexRoute = ConstructorIndexRouteImport.update({
  id: '/constructor/',
  path: '/constructor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateQuestionsRoute = ApiGenerateQuestionsRouteImport.update({
  id: '/api/generate-questions',
  path: '/api/generate-questions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate-questions': typeof ApiGenerateQuestionsRoute
  '/constructor/': typeof ConstructorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate-questions': typeof ApiGenerateQuestionsRoute
  '/constructor': typeof ConstructorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/generate-questions': typeof ApiGenerateQuestionsRoute
  '/constructor/': typeof ConstructorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/generate-questions' | '/constructor/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/generate-questions' | '/constructor'
  id: '__root__' | '/' | '/api/generate-questions' | '/constructor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGenerateQuestionsRoute: typeof ApiGenerateQuestionsRoute
  ConstructorIndexRoute: typeof ConstructorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constructor/': {
      id: '/constructor/'
      path: '/constructor'
      fullPath: '/constructor/'
      preLoaderRoute: typeof ConstructorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-questions': {
      id: '/api/generate-questions'
      path: '/api/generate-questions'
      fullPath: '/api/generate-questions'
      preLoaderRoute: typeof ApiGenerateQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGenerateQuestionsRoute: ApiGenerateQuestionsRoute,
  ConstructorIndexRoute: ConstructorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
